version: '3.8'

services:
  user-service:
    image: yourdockerhub/user-service:latest
    ports:
      - "8081:8080"
    networks:
      - app-network

  order-service:
    image: yourdockerhub/order-service:latest
    ports:
      - "8082:8080"
    networks:
      - app-network

  payment-service:
    image: yourdockerhub/payment-service:latest
    ports:
      - "8083:8080"
    networks:
      - app-network

networks:
  app-network:
